#!/usr/bin/env bash
#comment
LC_ALL=C
less /etc/passwd | while IFS= read -r line;do
USERNAME=$(printf "..%s.." "'$line'" | cut -d ":" -f1)
GROUP_ID=$(printf "..%s.." "'$line'" | cut -d ":" -f4)
HOME_DIRECTORY=$(printf "..%s.." "'$line'" | cut -d ":" -f6)
COMMANDSHELL=$(printf "..%s.." "'$line'" | cut -d ":" -f7)
USERID=$(printf "..%s.." "'$line'" | cut -d ":" -f3)
PASSWORD=$(printf "..%s.." "'$line'" | cut -d ":" -f2)
USERIDINFO=$(printf "..%s.." "'$line'" | cut -d ":" -f5)
echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMANDSHELL. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"
done
