#!/usr/bin/env bash
# Pour i equivalent à 0 tant que i est different de 10, ajoute 1 et si i=4 affiche "bad luck" si i=8 affiche "good luck" sinon affiche "Best School" 
i=0
while [ $i != 10 ]
do 
	i=$((i+1))
	if [ $i == 4 ]
	then	
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi		
done
