#!/usr/bin/env bash
#comments
i=0
while [ $i != 20 ]; do
	i=$((i+1))
case $i in
  1 | 2 | 3 | 5 | 6 | 7 | 8 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 18 | 19 | 20)echo $i;;
  4)echo $i
	echo "bad luck from China"  ;;
  9)echo $i
	  echo "bad luck from Japan";;
  17)echo $i
	  echo "bad luck from Italy";;
esac
done
