#!/usr/bin/env bash
# tant que h est different de 13 affiche "Hour: $h" ET AUSSI i tant que i est different de 59. 1 boucle incluse dans la premiere
i=0
h=0
while [ $h != 13 ];do
	echo "Hour: $h"
	h=$((h+1))
	i=0
while [ $i != 59 ];do
	i=$((i+1))
	echo $i
done
done
