#!/usr/bin/env bash
# Pour chaque résultat (ligne) affiche en interpretant les caracteres speciaux le contenu de tata et affiche que la 2eme colonnedans la separation est un tiret
for tata in *
do echo -e "$tata" | cut -d "-" -f2 
done
