#!/usr/bin/env bash
#comments
while true;do
mypid=/var/run/myscript.pid
echo $$ > $mypid
echo "To infinity and beyond"
sleep 1
trap 'echo "I hate the kill command"; rm '$mypid'; exit' SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap 'rm '$mypid'; exit' SIGQUIT
done
